"""Company-specific earnings document parsers."""

from cbr_trading.earnings.contracts import EarningsMarketRule
from cbr_trading.earnings.parsers.apple import (
    AppleGaapDilutedEpsParser,
    aapl_q3_2026_shadow_rule,
)
from cbr_trading.earnings.parsers.amazon import (
    AmazonGaapDilutedEpsParser,
    amzn_q2_2026_shadow_rule,
)
from cbr_trading.earnings.parsers.bed_bath_beyond import (
    BedBathBeyondNonGaapEpsParser,
    bbby_q2_2026_shadow_rule,
)
from cbr_trading.earnings.parsers.boeing import (
    BoeingCoreEpsParser,
    ba_q2_2026_shadow_rule,
)
from cbr_trading.earnings.parsers.caesars import (
    CaesarsGaapEpsParser,
    czr_q2_2026_shadow_rule,
)
from cbr_trading.earnings.parsers.costar import (
    CostarGaapEpsParser,
    csgp_q2_2026_shadow_rule,
)
from cbr_trading.earnings.parsers.dolby import (
    DolbyNonGaapDilutedEpsParser,
    dlb_q3_2026_shadow_rule,
)
from cbr_trading.earnings.parsers.july_28_sec import (
    CocaColaComparableEpsParser,
    FordAdjustedDilutedEpsParser,
    HiltonAdjustedDilutedEpsParser,
    InvescoAdjustedDilutedEpsParser,
    JetBlueAdjustedDilutedEpsParser,
    PayPalNonGaapEpsParser,
    SpGlobalAdjustedDilutedEpsParser,
    StarbucksGaapEpsParser,
    UpsAdjustedDilutedEpsParser,
    VisaNonGaapEpsParser,
    ford_q2_2026_shadow_rule,
    hlt_q2_2026_shadow_rule,
    ivz_q2_2026_shadow_rule,
    jblu_q2_2026_shadow_rule,
    ko_q2_2026_shadow_rule,
    pypl_q2_2026_shadow_rule,
    sbux_q3_2026_shadow_rule,
    spgi_q2_2026_shadow_rule,
    ups_q2_2026_shadow_rule,
    visa_q3_2026_shadow_rule,
)
from cbr_trading.earnings.parsers.july_29_sec import (
    AresCapitalCoreEpsParser,
    CbreGaapEpsParser,
    ElectronicArtsGaapEpsParser,
    EbayNonGaapEpsParser,
    GarminProFormaDilutedEpsParser,
    HumanaAdjustedEpsParser,
    IntegraAdjustedDilutedEpsParser,
    MetaGaapEpsParser,
    MicrosoftGaapEpsParser,
    PenskeAutomotiveGaapEpsParser,
    ProcterGambleCoreEpsParser,
    QualcommNonGaapEpsParser,
    RobinhoodGaapEpsParser,
    SofiGaapEpsParser,
    WaystarNonGaapEpsParser,
    WingstopGaapEpsParser,
    arcc_q2_2026_shadow_rule,
    cbre_q2_2026_shadow_rule,
    ea_q1_2027_shadow_rule,
    ebay_q2_2026_shadow_rule,
    grmn_q2_2026_shadow_rule,
    hood_q2_2026_shadow_rule,
    hum_q2_2026_shadow_rule,
    iart_q2_2026_shadow_rule,
    meta_q2_2026_shadow_rule,
    msft_q4_2026_shadow_rule,
    pag_q2_2026_shadow_rule,
    pg_q4_2026_shadow_rule,
    qcom_q3_2026_shadow_rule,
    sofi_q2_2026_shadow_rule,
    way_q2_2026_shadow_rule,
    wing_q2_2026_shadow_rule,
)
from cbr_trading.earnings.parsers.july_30_sec import (
    CignaAdjustedIncomePerShareParser,
    IceAdjustedDilutedEpsParser,
    MastercardAdjustedDilutedEpsParser,
    VirtuNormalizedAdjustedEpsParser,
    YumEpsExcludingSpecialItemsParser,
    ci_q2_2026_shadow_rule,
    ice_q2_2026_shadow_rule,
    mastercard_q2_2026_shadow_rule,
    virt_q2_2026_shadow_rule,
    yum_q2_2026_shadow_rule,
)
from cbr_trading.earnings.parsers.navitas import (
    NavitasEpsParser,
    nvts_q2_2026_shadow_rule,
)
from cbr_trading.earnings.parsers.nxp import (
    NxpNonGaapEpsParser,
    nxpi_q2_2026_shadow_rule,
)
from cbr_trading.earnings.parsers.royal_caribbean import (
    RoyalCaribbeanAdjustedEpsParser,
    rcl_q2_2026_shadow_rule,
)
from cbr_trading.earnings.parsers.reddit import (
    RedditGaapDilutedEpsParser,
    rddt_q2_2026_shadow_rule,
)
from cbr_trading.earnings.parsers.rivian import (
    RivianGaapDilutedEpsParser,
    rivn_q2_2026_shadow_rule,
)
from cbr_trading.earnings.parsers.roblox import (
    RobloxGaapDilutedEpsParser,
    rblx_q2_2026_shadow_rule,
)
from cbr_trading.earnings.parsers.woodward import (
    WoodwardGaapEpsParser,
    wwd_q3_2026_shadow_rule,
)


def earnings_parser_registry() -> dict[str, object]:
    return {
        "AAPL": AppleGaapDilutedEpsParser(),
        "AMZN": AmazonGaapDilutedEpsParser(),
        "ARCC": AresCapitalCoreEpsParser(),
        "BA": BoeingCoreEpsParser(),
        "BBBY": BedBathBeyondNonGaapEpsParser(),
        "CBRE": CbreGaapEpsParser(),
        "CI": CignaAdjustedIncomePerShareParser(),
        "CSGP": CostarGaapEpsParser(),
        "CZR": CaesarsGaapEpsParser(),
        "DLB": DolbyNonGaapDilutedEpsParser(),
        "EA": ElectronicArtsGaapEpsParser(),
        "EBAY": EbayNonGaapEpsParser(),
        "F": FordAdjustedDilutedEpsParser(),
        "GRMN": GarminProFormaDilutedEpsParser(),
        "HLT": HiltonAdjustedDilutedEpsParser(),
        "HOOD": RobinhoodGaapEpsParser(),
        "HUM": HumanaAdjustedEpsParser(),
        "IART": IntegraAdjustedDilutedEpsParser(),
        "IVZ": InvescoAdjustedDilutedEpsParser(),
        "ICE": IceAdjustedDilutedEpsParser(),
        "JBLU": JetBlueAdjustedDilutedEpsParser(),
        "KO": CocaColaComparableEpsParser(),
        "MA": MastercardAdjustedDilutedEpsParser(),
        "META": MetaGaapEpsParser(),
        "MSFT": MicrosoftGaapEpsParser(),
        "NVTS": NavitasEpsParser(),
        "NXPI": NxpNonGaapEpsParser(),
        "PAG": PenskeAutomotiveGaapEpsParser(),
        "PG": ProcterGambleCoreEpsParser(),
        "PYPL": PayPalNonGaapEpsParser(),
        "QCOM": QualcommNonGaapEpsParser(),
        "RCL": RoyalCaribbeanAdjustedEpsParser(),
        "RDDT": RedditGaapDilutedEpsParser(),
        "RIVN": RivianGaapDilutedEpsParser(),
        "RBLX": RobloxGaapDilutedEpsParser(),
        "SBUX": StarbucksGaapEpsParser(),
        "SOFI": SofiGaapEpsParser(),
        "SPGI": SpGlobalAdjustedDilutedEpsParser(),
        "UPS": UpsAdjustedDilutedEpsParser(),
        "V": VisaNonGaapEpsParser(),
        "VIRT": VirtuNormalizedAdjustedEpsParser(),
        "WAY": WaystarNonGaapEpsParser(),
        "WING": WingstopGaapEpsParser(),
        "WWD": WoodwardGaapEpsParser(),
        "YUM": YumEpsExcludingSpecialItemsParser(),
    }


def checked_in_shadow_rules() -> tuple[EarningsMarketRule, ...]:
    return (
        aapl_q3_2026_shadow_rule(),
        amzn_q2_2026_shadow_rule(),
        arcc_q2_2026_shadow_rule(),
        ba_q2_2026_shadow_rule(),
        csgp_q2_2026_shadow_rule(),
        czr_q2_2026_shadow_rule(),
        cbre_q2_2026_shadow_rule(),
        dlb_q3_2026_shadow_rule(),
        ci_q2_2026_shadow_rule(),
        ea_q1_2027_shadow_rule(),
        ebay_q2_2026_shadow_rule(),
        ford_q2_2026_shadow_rule(),
        grmn_q2_2026_shadow_rule(),
        hlt_q2_2026_shadow_rule(),
        hood_q2_2026_shadow_rule(),
        hum_q2_2026_shadow_rule(),
        iart_q2_2026_shadow_rule(),
        ivz_q2_2026_shadow_rule(),
        ice_q2_2026_shadow_rule(),
        jblu_q2_2026_shadow_rule(),
        ko_q2_2026_shadow_rule(),
        mastercard_q2_2026_shadow_rule(),
        meta_q2_2026_shadow_rule(),
        msft_q4_2026_shadow_rule(),
        nvts_q2_2026_shadow_rule(),
        nxpi_q2_2026_shadow_rule(),
        pag_q2_2026_shadow_rule(),
        pg_q4_2026_shadow_rule(),
        pypl_q2_2026_shadow_rule(),
        qcom_q3_2026_shadow_rule(),
        rcl_q2_2026_shadow_rule(),
        rddt_q2_2026_shadow_rule(),
        rivn_q2_2026_shadow_rule(),
        rblx_q2_2026_shadow_rule(),
        sbux_q3_2026_shadow_rule(),
        sofi_q2_2026_shadow_rule(),
        spgi_q2_2026_shadow_rule(),
        ups_q2_2026_shadow_rule(),
        visa_q3_2026_shadow_rule(),
        virt_q2_2026_shadow_rule(),
        way_q2_2026_shadow_rule(),
        wing_q2_2026_shadow_rule(),
        wwd_q3_2026_shadow_rule(),
        yum_q2_2026_shadow_rule(),
        bbby_q2_2026_shadow_rule(),
    )

__all__ = [
    "AppleGaapDilutedEpsParser",
    "AmazonGaapDilutedEpsParser",
    "AresCapitalCoreEpsParser",
    "BedBathBeyondNonGaapEpsParser",
    "BoeingCoreEpsParser",
    "CbreGaapEpsParser",
    "CignaAdjustedIncomePerShareParser",
    "CaesarsGaapEpsParser",
    "CocaColaComparableEpsParser",
    "CostarGaapEpsParser",
    "DolbyNonGaapDilutedEpsParser",
    "ElectronicArtsGaapEpsParser",
    "EbayNonGaapEpsParser",
    "FordAdjustedDilutedEpsParser",
    "GarminProFormaDilutedEpsParser",
    "HiltonAdjustedDilutedEpsParser",
    "HumanaAdjustedEpsParser",
    "IntegraAdjustedDilutedEpsParser",
    "InvescoAdjustedDilutedEpsParser",
    "IceAdjustedDilutedEpsParser",
    "JetBlueAdjustedDilutedEpsParser",
    "MastercardAdjustedDilutedEpsParser",
    "MetaGaapEpsParser",
    "MicrosoftGaapEpsParser",
    "NavitasEpsParser",
    "NxpNonGaapEpsParser",
    "PayPalNonGaapEpsParser",
    "PenskeAutomotiveGaapEpsParser",
    "ProcterGambleCoreEpsParser",
    "QualcommNonGaapEpsParser",
    "RobinhoodGaapEpsParser",
    "RoyalCaribbeanAdjustedEpsParser",
    "RedditGaapDilutedEpsParser",
    "RivianGaapDilutedEpsParser",
    "RobloxGaapDilutedEpsParser",
    "SofiGaapEpsParser",
    "SpGlobalAdjustedDilutedEpsParser",
    "StarbucksGaapEpsParser",
    "UpsAdjustedDilutedEpsParser",
    "VisaNonGaapEpsParser",
    "VirtuNormalizedAdjustedEpsParser",
    "WaystarNonGaapEpsParser",
    "WingstopGaapEpsParser",
    "WoodwardGaapEpsParser",
    "YumEpsExcludingSpecialItemsParser",
    "ba_q2_2026_shadow_rule",
    "aapl_q3_2026_shadow_rule",
    "arcc_q2_2026_shadow_rule",
    "amzn_q2_2026_shadow_rule",
    "bbby_q2_2026_shadow_rule",
    "checked_in_shadow_rules",
    "csgp_q2_2026_shadow_rule",
    "cbre_q2_2026_shadow_rule",
    "ci_q2_2026_shadow_rule",
    "czr_q2_2026_shadow_rule",
    "dlb_q3_2026_shadow_rule",
    "ea_q1_2027_shadow_rule",
    "ebay_q2_2026_shadow_rule",
    "earnings_parser_registry",
    "ford_q2_2026_shadow_rule",
    "grmn_q2_2026_shadow_rule",
    "hlt_q2_2026_shadow_rule",
    "hood_q2_2026_shadow_rule",
    "hum_q2_2026_shadow_rule",
    "iart_q2_2026_shadow_rule",
    "ivz_q2_2026_shadow_rule",
    "ice_q2_2026_shadow_rule",
    "jblu_q2_2026_shadow_rule",
    "ko_q2_2026_shadow_rule",
    "mastercard_q2_2026_shadow_rule",
    "meta_q2_2026_shadow_rule",
    "msft_q4_2026_shadow_rule",
    "nvts_q2_2026_shadow_rule",
    "nxpi_q2_2026_shadow_rule",
    "pag_q2_2026_shadow_rule",
    "pg_q4_2026_shadow_rule",
    "pypl_q2_2026_shadow_rule",
    "qcom_q3_2026_shadow_rule",
    "rcl_q2_2026_shadow_rule",
    "rddt_q2_2026_shadow_rule",
    "rivn_q2_2026_shadow_rule",
    "rblx_q2_2026_shadow_rule",
    "sbux_q3_2026_shadow_rule",
    "sofi_q2_2026_shadow_rule",
    "spgi_q2_2026_shadow_rule",
    "ups_q2_2026_shadow_rule",
    "visa_q3_2026_shadow_rule",
    "virt_q2_2026_shadow_rule",
    "way_q2_2026_shadow_rule",
    "wing_q2_2026_shadow_rule",
    "wwd_q3_2026_shadow_rule",
    "yum_q2_2026_shadow_rule",
]
