"""Company-specific earnings document parsers."""

from cbr_trading.earnings.contracts import EarningsMarketRule
from cbr_trading.earnings.parsers.bed_bath_beyond import (
    BedBathBeyondNonGaapEpsParser,
    bbby_q2_2026_shadow_rule,
)
from cbr_trading.earnings.parsers.boeing import (
    BoeingCoreEpsParser,
    ba_q2_2026_shadow_rule,
)
from cbr_trading.earnings.parsers.caesars import (
    CaesarsGaapEpsParser,
    czr_q2_2026_shadow_rule,
)
from cbr_trading.earnings.parsers.costar import (
    CostarGaapEpsParser,
    csgp_q2_2026_shadow_rule,
)
from cbr_trading.earnings.parsers.july_28_sec import (
    CocaColaComparableEpsParser,
    FordAdjustedDilutedEpsParser,
    HiltonAdjustedDilutedEpsParser,
    InvescoAdjustedDilutedEpsParser,
    JetBlueAdjustedDilutedEpsParser,
    PayPalNonGaapEpsParser,
    SpGlobalAdjustedDilutedEpsParser,
    StarbucksGaapEpsParser,
    UpsAdjustedDilutedEpsParser,
    VisaNonGaapEpsParser,
    ford_q2_2026_shadow_rule,
    hlt_q2_2026_shadow_rule,
    ivz_q2_2026_shadow_rule,
    jblu_q2_2026_shadow_rule,
    ko_q2_2026_shadow_rule,
    pypl_q2_2026_shadow_rule,
    sbux_q3_2026_shadow_rule,
    spgi_q2_2026_shadow_rule,
    ups_q2_2026_shadow_rule,
    visa_q3_2026_shadow_rule,
)
from cbr_trading.earnings.parsers.july_29_sec import (
    EbayNonGaapEpsParser,
    HumanaAdjustedEpsParser,
    MetaGaapEpsParser,
    MicrosoftGaapEpsParser,
    ProcterGambleCoreEpsParser,
    QualcommNonGaapEpsParser,
    RobinhoodGaapEpsParser,
    SofiGaapEpsParser,
    ebay_q2_2026_shadow_rule,
    hood_q2_2026_shadow_rule,
    hum_q2_2026_shadow_rule,
    meta_q2_2026_shadow_rule,
    msft_q4_2026_shadow_rule,
    pg_q4_2026_shadow_rule,
    qcom_q3_2026_shadow_rule,
    sofi_q2_2026_shadow_rule,
)
from cbr_trading.earnings.parsers.navitas import (
    NavitasEpsParser,
    nvts_q2_2026_shadow_rule,
)
from cbr_trading.earnings.parsers.nxp import (
    NxpNonGaapEpsParser,
    nxpi_q2_2026_shadow_rule,
)
from cbr_trading.earnings.parsers.royal_caribbean import (
    RoyalCaribbeanAdjustedEpsParser,
    rcl_q2_2026_shadow_rule,
)
from cbr_trading.earnings.parsers.woodward import (
    WoodwardGaapEpsParser,
    wwd_q3_2026_shadow_rule,
)


def earnings_parser_registry() -> dict[str, object]:
    return {
        "BA": BoeingCoreEpsParser(),
        "BBBY": BedBathBeyondNonGaapEpsParser(),
        "CSGP": CostarGaapEpsParser(),
        "CZR": CaesarsGaapEpsParser(),
        "EBAY": EbayNonGaapEpsParser(),
        "F": FordAdjustedDilutedEpsParser(),
        "HLT": HiltonAdjustedDilutedEpsParser(),
        "HOOD": RobinhoodGaapEpsParser(),
        "HUM": HumanaAdjustedEpsParser(),
        "IVZ": InvescoAdjustedDilutedEpsParser(),
        "JBLU": JetBlueAdjustedDilutedEpsParser(),
        "KO": CocaColaComparableEpsParser(),
        "META": MetaGaapEpsParser(),
        "MSFT": MicrosoftGaapEpsParser(),
        "NVTS": NavitasEpsParser(),
        "NXPI": NxpNonGaapEpsParser(),
        "PG": ProcterGambleCoreEpsParser(),
        "PYPL": PayPalNonGaapEpsParser(),
        "QCOM": QualcommNonGaapEpsParser(),
        "RCL": RoyalCaribbeanAdjustedEpsParser(),
        "SBUX": StarbucksGaapEpsParser(),
        "SOFI": SofiGaapEpsParser(),
        "SPGI": SpGlobalAdjustedDilutedEpsParser(),
        "UPS": UpsAdjustedDilutedEpsParser(),
        "V": VisaNonGaapEpsParser(),
        "WWD": WoodwardGaapEpsParser(),
    }


def checked_in_shadow_rules() -> tuple[EarningsMarketRule, ...]:
    return (
        ba_q2_2026_shadow_rule(),
        csgp_q2_2026_shadow_rule(),
        czr_q2_2026_shadow_rule(),
        ebay_q2_2026_shadow_rule(),
        ford_q2_2026_shadow_rule(),
        hlt_q2_2026_shadow_rule(),
        hood_q2_2026_shadow_rule(),
        hum_q2_2026_shadow_rule(),
        ivz_q2_2026_shadow_rule(),
        jblu_q2_2026_shadow_rule(),
        ko_q2_2026_shadow_rule(),
        meta_q2_2026_shadow_rule(),
        msft_q4_2026_shadow_rule(),
        nvts_q2_2026_shadow_rule(),
        nxpi_q2_2026_shadow_rule(),
        pg_q4_2026_shadow_rule(),
        pypl_q2_2026_shadow_rule(),
        qcom_q3_2026_shadow_rule(),
        rcl_q2_2026_shadow_rule(),
        sbux_q3_2026_shadow_rule(),
        sofi_q2_2026_shadow_rule(),
        spgi_q2_2026_shadow_rule(),
        ups_q2_2026_shadow_rule(),
        visa_q3_2026_shadow_rule(),
        wwd_q3_2026_shadow_rule(),
        bbby_q2_2026_shadow_rule(),
    )

__all__ = [
    "BedBathBeyondNonGaapEpsParser",
    "BoeingCoreEpsParser",
    "CaesarsGaapEpsParser",
    "CocaColaComparableEpsParser",
    "CostarGaapEpsParser",
    "EbayNonGaapEpsParser",
    "FordAdjustedDilutedEpsParser",
    "HiltonAdjustedDilutedEpsParser",
    "HumanaAdjustedEpsParser",
    "InvescoAdjustedDilutedEpsParser",
    "JetBlueAdjustedDilutedEpsParser",
    "MetaGaapEpsParser",
    "MicrosoftGaapEpsParser",
    "NavitasEpsParser",
    "NxpNonGaapEpsParser",
    "PayPalNonGaapEpsParser",
    "ProcterGambleCoreEpsParser",
    "QualcommNonGaapEpsParser",
    "RobinhoodGaapEpsParser",
    "RoyalCaribbeanAdjustedEpsParser",
    "SofiGaapEpsParser",
    "SpGlobalAdjustedDilutedEpsParser",
    "StarbucksGaapEpsParser",
    "UpsAdjustedDilutedEpsParser",
    "VisaNonGaapEpsParser",
    "WoodwardGaapEpsParser",
    "ba_q2_2026_shadow_rule",
    "bbby_q2_2026_shadow_rule",
    "checked_in_shadow_rules",
    "csgp_q2_2026_shadow_rule",
    "czr_q2_2026_shadow_rule",
    "ebay_q2_2026_shadow_rule",
    "earnings_parser_registry",
    "ford_q2_2026_shadow_rule",
    "hlt_q2_2026_shadow_rule",
    "hood_q2_2026_shadow_rule",
    "hum_q2_2026_shadow_rule",
    "ivz_q2_2026_shadow_rule",
    "jblu_q2_2026_shadow_rule",
    "ko_q2_2026_shadow_rule",
    "meta_q2_2026_shadow_rule",
    "msft_q4_2026_shadow_rule",
    "nvts_q2_2026_shadow_rule",
    "nxpi_q2_2026_shadow_rule",
    "pg_q4_2026_shadow_rule",
    "pypl_q2_2026_shadow_rule",
    "qcom_q3_2026_shadow_rule",
    "rcl_q2_2026_shadow_rule",
    "sbux_q3_2026_shadow_rule",
    "sofi_q2_2026_shadow_rule",
    "spgi_q2_2026_shadow_rule",
    "ups_q2_2026_shadow_rule",
    "visa_q3_2026_shadow_rule",
    "wwd_q3_2026_shadow_rule",
]
