-- Additive migration for the universal OrderSupervisor.
-- This migration intentionally does not alter or drop any legacy object.

CREATE TABLE IF NOT EXISTS resolution_order_groups (
    order_group_id text PRIMARY KEY,
    intent_id text NOT NULL UNIQUE,
    signal_id text,
    template_id text,
    strategy_id text,
    account_name text NOT NULL,
    condition_id text NOT NULL,
    outcome text NOT NULL CHECK (outcome IN ('YES', 'NO')),
    asset_id text NOT NULL,
    side text CHECK (side IS NULL OR side IN ('BUY', 'SELL')),
    desired_price numeric(20, 10),
    quantity numeric(38, 18),
    notional numeric(38, 18),
    policy_kind text NOT NULL
        CHECK (policy_kind IN ('keep_open', 'reprice_on_tick_change')),
    trigger_old_tick numeric(20, 10),
    trigger_new_tick numeric(20, 10),
    max_reprices integer NOT NULL DEFAULT 0
        CHECK (max_reprices >= 0),
    reprice_count integer NOT NULL DEFAULT 0
        CHECK (reprice_count >= 0 AND reprice_count <= max_reprices),
    status text NOT NULL DEFAULT 'ACTIVE'
        CHECK (
            status IN (
                'ACTIVE',
                'REPRICING',
                'COMPLETED',
                'FAILED',
                'CANCELLED'
            )
        ),
    revision bigint NOT NULL DEFAULT 0 CHECK (revision >= 0),
    last_error text,
    metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CHECK (
        (quantity IS NULL) <> (notional IS NULL)
        OR (quantity IS NULL AND notional IS NULL)
    ),
    CHECK (desired_price IS NULL OR (desired_price > 0 AND desired_price < 1)),
    CHECK (
        (
            policy_kind = 'keep_open'
            AND trigger_old_tick IS NULL
            AND trigger_new_tick IS NULL
            AND max_reprices = 0
        )
        OR
        (
            policy_kind = 'reprice_on_tick_change'
            AND trigger_old_tick > trigger_new_tick
            AND trigger_new_tick > 0
            AND max_reprices > 0
            AND side IS NOT NULL
            AND desired_price IS NOT NULL
            AND ((quantity IS NULL) <> (notional IS NULL))
        )
    )
);

CREATE INDEX IF NOT EXISTS ix_resolution_order_groups_active_asset
    ON resolution_order_groups (asset_id, status)
    WHERE status IN ('ACTIVE', 'REPRICING');

CREATE TABLE IF NOT EXISTS resolution_order_group_orders (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_group_id text NOT NULL
        REFERENCES resolution_order_groups (order_group_id)
        ON DELETE RESTRICT,
    order_id text NOT NULL UNIQUE,
    generation integer NOT NULL DEFAULT 0 CHECK (generation >= 0),
    status text NOT NULL DEFAULT 'LIVE'
        CHECK (
            status IN (
                'LIVE',
                'CANCELLED',
                'REPLACED',
                'FILLED',
                'REJECTED',
                'UNKNOWN'
            )
        ),
    effective_price numeric(20, 10),
    quantity numeric(38, 18),
    parent_order_id text,
    metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
    opened_at timestamptz NOT NULL DEFAULT now(),
    closed_at timestamptz,
    updated_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (order_group_id, order_id),
    CHECK (
        effective_price IS NULL
        OR (effective_price > 0 AND effective_price < 1)
    ),
    CHECK (quantity IS NULL OR quantity > 0)
);

CREATE INDEX IF NOT EXISTS ix_resolution_group_orders_live
    ON resolution_order_group_orders (order_group_id, status)
    WHERE status = 'LIVE';

CREATE TABLE IF NOT EXISTS resolution_supervision_events (
    event_id text NOT NULL,
    order_group_id text NOT NULL
        REFERENCES resolution_order_groups (order_group_id)
        ON DELETE RESTRICT,
    event_type text NOT NULL,
    status text NOT NULL DEFAULT 'RECEIVED'
        CHECK (
            status IN (
                'RECEIVED',
                'CLAIMED',
                'COMPLETED',
                'FAILED',
                'IGNORED'
            )
        ),
    asset_id text NOT NULL,
    old_tick numeric(20, 10),
    new_tick numeric(20, 10),
    observed_at timestamptz NOT NULL,
    claimed_revision bigint,
    error text,
    payload jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (event_id, order_group_id),
    CHECK (old_tick IS NULL OR old_tick > 0),
    CHECK (new_tick IS NULL OR new_tick > 0)
);

CREATE INDEX IF NOT EXISTS ix_resolution_supervision_events_status
    ON resolution_supervision_events (status, observed_at);
