-- Additive source-neutral idempotency ledger for PreparedExecutor.
-- This migration intentionally does not alter or drop any legacy object.

CREATE TABLE IF NOT EXISTS resolution_execution_claims (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    idempotency_key text NOT NULL,
    scope_id text NOT NULL,
    template_id text NOT NULL,
    strategy_id text NOT NULL,
    source text NOT NULL,
    source_reference text NOT NULL,
    account_name text NOT NULL,
    condition_id text NOT NULL,
    outcome text NOT NULL CHECK (outcome IN ('YES', 'NO')),
    side text NOT NULL CHECK (side IN ('BUY', 'SELL')),
    desired_price numeric(20, 10) NOT NULL
        CHECK (desired_price > 0 AND desired_price < 1),
    effective_price numeric(20, 10) NOT NULL
        CHECK (effective_price > 0 AND effective_price < 1),
    quantity numeric(38, 18),
    notional numeric(38, 18),
    status text NOT NULL DEFAULT 'PENDING'
        CHECK (
            status IN (
                'PENDING',
                'EXECUTED',
                'REJECTED',
                'ERROR',
                'EXPIRED'
            )
        ),
    result jsonb,
    error text,
    metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    completed_at timestamptz,
    CHECK ((quantity IS NULL) <> (notional IS NULL)),
    CHECK (quantity IS NULL OR quantity > 0),
    CHECK (notional IS NULL OR notional > 0)
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_resolution_execution_claims_key
    ON resolution_execution_claims (idempotency_key);

CREATE UNIQUE INDEX IF NOT EXISTS ux_resolution_execution_claims_scope_template
    ON resolution_execution_claims (scope_id, template_id);

CREATE INDEX IF NOT EXISTS ix_resolution_execution_claims_pending
    ON resolution_execution_claims (status, updated_at)
    WHERE status = 'PENDING';
