-- Additive shadow-ingestion schema for company earnings resolution sources.
-- This migration intentionally does not alter or drop any legacy object.

CREATE TABLE IF NOT EXISTS earnings_market_rules (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rule_key text NOT NULL,
    scope_id text NOT NULL,
    ticker text NOT NULL,
    cik text NOT NULL,
    fiscal_year integer NOT NULL,
    fiscal_quarter smallint NOT NULL
        CHECK (fiscal_quarter BETWEEN 1 AND 4),
    period_end date NOT NULL,
    estimated_release_at timestamptz NOT NULL,
    metric_kind text NOT NULL,
    primary_basis text NOT NULL,
    fallback_basis text NOT NULL,
    comparison_op text NOT NULL
        CHECK (comparison_op IN ('>', '>=', '<', '<=', '==')),
    strike numeric(20, 10) NOT NULL,
    rounding_places smallint NOT NULL DEFAULT 2
        CHECK (rounding_places BETWEEN 0 AND 6),
    currency text NOT NULL DEFAULT 'USD',
    market_slug text,
    condition_id text,
    source_policy jsonb NOT NULL DEFAULT '{}'::jsonb,
    fallback_policy jsonb NOT NULL DEFAULT '{}'::jsonb,
    status text NOT NULL DEFAULT 'SHADOW'
        CHECK (status IN ('SHADOW', 'WATCHING', 'DISABLED')),
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_earnings_market_rules_rule_key
    ON earnings_market_rules (rule_key);

CREATE UNIQUE INDEX IF NOT EXISTS ux_earnings_market_rules_scope_id
    ON earnings_market_rules (scope_id);

CREATE UNIQUE INDEX IF NOT EXISTS ux_earnings_market_rules_condition_id
    ON earnings_market_rules (condition_id)
    WHERE condition_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS ix_earnings_market_rules_watch
    ON earnings_market_rules (status, estimated_release_at, ticker);

CREATE TABLE IF NOT EXISTS earnings_source_events (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    idempotency_key text NOT NULL,
    rule_id bigint NOT NULL
        REFERENCES earnings_market_rules(id),
    scope_id text NOT NULL,
    provider text NOT NULL,
    provider_event_id text NOT NULL,
    ticker text NOT NULL,
    cik text NOT NULL,
    form_type text NOT NULL,
    items jsonb NOT NULL DEFAULT '[]'::jsonb,
    document_type text NOT NULL,
    source_url text NOT NULL,
    filing_url text NOT NULL,
    filed_at timestamptz NOT NULL,
    received_at timestamptz NOT NULL,
    authority text NOT NULL,
    transport_fingerprint text NOT NULL,
    metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
    status text NOT NULL DEFAULT 'RECEIVED'
        CHECK (
            status IN (
                'RECEIVED',
                'FETCHED',
                'PARSED',
                'NO_MATCH',
                'QUARANTINED',
                'ERROR'
            )
        ),
    error text,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_earnings_source_events_key
    ON earnings_source_events (idempotency_key);

CREATE UNIQUE INDEX IF NOT EXISTS ux_earnings_source_events_provider_doc
    ON earnings_source_events (
        scope_id,
        provider,
        provider_event_id,
        source_url
    );

CREATE INDEX IF NOT EXISTS ix_earnings_source_events_status
    ON earnings_source_events (status, received_at);

CREATE INDEX IF NOT EXISTS ix_earnings_source_events_scope
    ON earnings_source_events (scope_id, filed_at);

CREATE TABLE IF NOT EXISTS earnings_fact_candidates (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    idempotency_key text NOT NULL,
    source_event_id bigint NOT NULL
        REFERENCES earnings_source_events(id),
    scope_id text NOT NULL,
    ticker text NOT NULL,
    cik text NOT NULL,
    period_end date NOT NULL,
    metric_kind text NOT NULL,
    basis text NOT NULL,
    currency text NOT NULL,
    raw_value numeric(20, 10) NOT NULL,
    value numeric(20, 10) NOT NULL,
    authority text NOT NULL,
    provider text NOT NULL,
    parser_name text NOT NULL,
    parser_version text NOT NULL,
    confidence numeric(8, 7) NOT NULL
        CHECK (confidence BETWEEN 0 AND 1),
    document_fingerprint text NOT NULL,
    evidence jsonb NOT NULL DEFAULT '{}'::jsonb,
    status text NOT NULL DEFAULT 'VALIDATED'
        CHECK (
            status IN (
                'VALIDATED',
                'QUARANTINED',
                'EMITTED',
                'SUPERSEDED'
            )
        ),
    reason text NOT NULL,
    published_at timestamptz NOT NULL,
    detected_at timestamptz NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_earnings_fact_candidates_key
    ON earnings_fact_candidates (idempotency_key);

CREATE INDEX IF NOT EXISTS ix_earnings_fact_candidates_resolution
    ON earnings_fact_candidates (scope_id, status, detected_at);

CREATE INDEX IF NOT EXISTS ix_earnings_fact_candidates_source_event
    ON earnings_fact_candidates (source_event_id);
