-- Additive source-neutral execution configuration.
-- This migration intentionally does not alter or drop any legacy object.

CREATE TABLE IF NOT EXISTS resolution_execution_profiles (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    profile_key text NOT NULL,
    scope_id text NOT NULL,
    source_name text NOT NULL,
    source_reference text NOT NULL,
    account_name text NOT NULL,
    condition_id text NOT NULL,
    yes_desired_price numeric(20, 10) NOT NULL
        CHECK (
            yes_desired_price > 0
            AND yes_desired_price < 1
        ),
    no_desired_price numeric(20, 10) NOT NULL
        CHECK (
            no_desired_price > 0
            AND no_desired_price < 1
        ),
    quantity numeric(20, 10) NOT NULL
        CHECK (quantity > 0),
    lifecycle_kind text NOT NULL DEFAULT 'reprice_on_tick_change'
        CHECK (
            lifecycle_kind IN (
                'keep_open',
                'reprice_on_tick_change'
            )
        ),
    old_tick numeric(20, 10),
    new_tick numeric(20, 10),
    max_reprices integer,
    prepare_from timestamptz NOT NULL,
    expires_at timestamptz NOT NULL,
    metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
    status text NOT NULL DEFAULT 'DISABLED'
        CHECK (status IN ('DISABLED', 'ENABLED')),
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CHECK (expires_at > prepare_from),
    CHECK (
        (
            lifecycle_kind = 'keep_open'
            AND old_tick IS NULL
            AND new_tick IS NULL
            AND max_reprices IS NULL
        )
        OR
        (
            lifecycle_kind = 'reprice_on_tick_change'
            AND old_tick > 0
            AND new_tick > 0
            AND new_tick < old_tick
            AND max_reprices >= 1
        )
    )
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_resolution_execution_profiles_key
    ON resolution_execution_profiles (profile_key);

CREATE UNIQUE INDEX IF NOT EXISTS ux_resolution_execution_profiles_scope
    ON resolution_execution_profiles (scope_id);

CREATE INDEX IF NOT EXISTS ix_resolution_execution_profiles_enabled
    ON resolution_execution_profiles (
        status,
        source_name,
        prepare_from,
        expires_at
    );
