-- Additive source-neutral defaults for future execution profiles.
-- Existing execution profiles are intentionally left unchanged.

CREATE TABLE IF NOT EXISTS resolution_profile_templates (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    template_key text NOT NULL,
    yes_desired_price numeric(20, 10) NOT NULL
        CHECK (
            yes_desired_price > 0
            AND yes_desired_price < 1
        ),
    no_desired_price numeric(20, 10) NOT NULL
        CHECK (
            no_desired_price > 0
            AND no_desired_price < 1
        ),
    quantity numeric(20, 10) NOT NULL
        CHECK (quantity > 0),
    lifecycle_kind text NOT NULL DEFAULT 'reprice_on_tick_change'
        CHECK (
            lifecycle_kind IN (
                'keep_open',
                'reprice_on_tick_change'
            )
        ),
    old_tick numeric(20, 10),
    new_tick numeric(20, 10),
    max_reprices integer,
    metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CHECK (
        (
            lifecycle_kind = 'keep_open'
            AND old_tick IS NULL
            AND new_tick IS NULL
            AND max_reprices IS NULL
        )
        OR
        (
            lifecycle_kind = 'reprice_on_tick_change'
            AND old_tick > 0
            AND new_tick > 0
            AND new_tick < old_tick
            AND max_reprices >= 1
        )
    )
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_resolution_profile_templates_key
    ON resolution_profile_templates (template_key);

INSERT INTO resolution_profile_templates (
    template_key,
    yes_desired_price,
    no_desired_price,
    quantity,
    lifecycle_kind,
    old_tick,
    new_tick,
    max_reprices,
    metadata
)
VALUES (
    'default',
    0.999,
    0.999,
    50,
    'reprice_on_tick_change',
    0.01,
    0.001,
    1,
    '{"purpose":"operator_default"}'::jsonb
)
ON CONFLICT (template_key) DO NOTHING;
