-- Additive append-only holdings history for Strategy (MSTR) BTC updates.
-- This migration intentionally does not alter or drop any legacy object.

CREATE TABLE IF NOT EXISTS mstr_btc_holdings_state (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    holdings_btc bigint NOT NULL CHECK (holdings_btc >= 0),
    as_of timestamptz NOT NULL,
    observed_at timestamptz NOT NULL,
    provider text NOT NULL
        CHECK (provider IN ('sec', 'strategy_ledger')),
    provider_event_id text NOT NULL,
    source_url text NOT NULL,
    document_fingerprint text NOT NULL,
    predecessor_state_id bigint
        REFERENCES mstr_btc_holdings_state(id)
        ON DELETE RESTRICT,
    validation_status text NOT NULL
        CHECK (
            validation_status IN (
                'VALIDATED',
                'QUARANTINED'
            )
        ),
    attributes jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at timestamptz NOT NULL DEFAULT now(),
    CHECK (as_of <= observed_at),
    CHECK (
        predecessor_state_id IS NULL
        OR predecessor_state_id <> id
    )
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_mstr_btc_holdings_state_provider_event
    ON mstr_btc_holdings_state (
        provider,
        provider_event_id
    );

CREATE INDEX IF NOT EXISTS ix_mstr_btc_holdings_state_pin
    ON mstr_btc_holdings_state (
        as_of DESC,
        observed_at DESC,
        id DESC
    )
    WHERE validation_status = 'VALIDATED';

CREATE OR REPLACE FUNCTION reject_mstr_btc_holdings_state_mutation()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    RAISE EXCEPTION 'mstr_btc_holdings_state is append-only'
        USING ERRCODE = '55000';
END;
$$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_trigger
        WHERE tgrelid = 'mstr_btc_holdings_state'::regclass
          AND tgname = 'trg_mstr_btc_holdings_state_append_only'
          AND NOT tgisinternal
    ) THEN
        CREATE TRIGGER trg_mstr_btc_holdings_state_append_only
        BEFORE UPDATE OR DELETE ON mstr_btc_holdings_state
        FOR EACH ROW
        EXECUTE FUNCTION reject_mstr_btc_holdings_state_mutation();
    END IF;
END;
$$;
