-- Additive append-only source audit for Strategy (MSTR) BTC updates.
-- This migration intentionally does not alter or drop any legacy object.

CREATE TABLE IF NOT EXISTS mstr_btc_source_events (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    idempotency_key text NOT NULL,
    scope_id text NOT NULL,
    provider text NOT NULL CHECK (provider IN ('sec', 'strategy_ledger')),
    provider_event_id text NOT NULL,
    ticker text NOT NULL,
    cik text NOT NULL,
    form_type text NOT NULL,
    source_url text NOT NULL,
    filing_url text NOT NULL,
    filed_at timestamptz NOT NULL,
    received_at timestamptz NOT NULL,
    transport_fingerprint text NOT NULL,
    metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_mstr_btc_source_events_key
    ON mstr_btc_source_events (idempotency_key);

CREATE UNIQUE INDEX IF NOT EXISTS ux_mstr_btc_source_events_provider_doc
    ON mstr_btc_source_events (
        scope_id,
        provider,
        provider_event_id,
        source_url
    );

CREATE INDEX IF NOT EXISTS ix_mstr_btc_source_events_scope
    ON mstr_btc_source_events (scope_id, filed_at, id);

CREATE TABLE IF NOT EXISTS mstr_btc_fact_candidates (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    idempotency_key text NOT NULL,
    source_event_id bigint NOT NULL
        REFERENCES mstr_btc_source_events(id)
        ON DELETE RESTRICT,
    scope_id text NOT NULL,
    provider text NOT NULL CHECK (provider IN ('sec', 'strategy_ledger')),
    provider_event_id text NOT NULL,
    baseline_state_id bigint NOT NULL
        REFERENCES mstr_btc_holdings_state(id)
        ON DELETE RESTRICT,
    holdings_before_btc bigint NOT NULL CHECK (holdings_before_btc >= 0),
    holdings_after_btc bigint NOT NULL CHECK (holdings_after_btc >= 0),
    net_change_btc bigint NOT NULL,
    acquired_btc bigint CHECK (acquired_btc >= 0),
    sold_btc bigint CHECK (sold_btc >= 0),
    acquired_derivation text NOT NULL
        CHECK (
            acquired_derivation IN (
                'explicit',
                'holdings_delta',
                'not_confirmed'
            )
        ),
    sold_derivation text NOT NULL
        CHECK (
            sold_derivation IN (
                'explicit',
                'holdings_delta',
                'not_confirmed'
            )
        ),
    holdings_crosscheck_difference_btc bigint NOT NULL,
    published_at timestamptz NOT NULL,
    detected_at timestamptz NOT NULL,
    parser_name text NOT NULL,
    parser_version text NOT NULL,
    document_fingerprint text NOT NULL,
    evidence jsonb NOT NULL DEFAULT '[]'::jsonb,
    attributes jsonb NOT NULL DEFAULT '{}'::jsonb,
    reason text NOT NULL,
    validation_status text NOT NULL DEFAULT 'VALIDATED'
        CHECK (validation_status = 'VALIDATED'),
    created_at timestamptz NOT NULL DEFAULT now(),
    CHECK (
        net_change_btc = holdings_after_btc - holdings_before_btc
    ),
    CHECK (
        (acquired_btc IS NULL) =
        (acquired_derivation = 'not_confirmed')
    ),
    CHECK (
        (sold_btc IS NULL) =
        (sold_derivation = 'not_confirmed')
    )
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_mstr_btc_fact_candidates_key
    ON mstr_btc_fact_candidates (idempotency_key);

CREATE UNIQUE INDEX IF NOT EXISTS ux_mstr_btc_fact_candidates_event
    ON mstr_btc_fact_candidates (source_event_id);

CREATE INDEX IF NOT EXISTS ix_mstr_btc_fact_candidates_resolution
    ON mstr_btc_fact_candidates (
        scope_id,
        validation_status,
        detected_at,
        id
    );

CREATE TABLE IF NOT EXISTS mstr_btc_processing_results (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    idempotency_key text NOT NULL,
    source_event_id bigint NOT NULL
        REFERENCES mstr_btc_source_events(id)
        ON DELETE RESTRICT,
    status text NOT NULL
        CHECK (
            status IN (
                'ACCEPTED',
                'NO_MATCH',
                'QUARANTINED',
                'ERROR'
            )
        ),
    reason text NOT NULL,
    baseline_state_id bigint
        REFERENCES mstr_btc_holdings_state(id)
        ON DELETE RESTRICT,
    fact_candidate_id bigint
        REFERENCES mstr_btc_fact_candidates(id)
        ON DELETE RESTRICT,
    created_at timestamptz NOT NULL DEFAULT now(),
    CHECK (
        (status = 'ACCEPTED' AND fact_candidate_id IS NOT NULL)
        OR
        (status <> 'ACCEPTED' AND fact_candidate_id IS NULL)
    )
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_mstr_btc_processing_results_key
    ON mstr_btc_processing_results (idempotency_key);

CREATE UNIQUE INDEX IF NOT EXISTS ux_mstr_btc_processing_results_terminal
    ON mstr_btc_processing_results (source_event_id)
    WHERE status IN ('ACCEPTED', 'NO_MATCH', 'QUARANTINED');

CREATE INDEX IF NOT EXISTS ix_mstr_btc_processing_results_event
    ON mstr_btc_processing_results (source_event_id, created_at, id);

CREATE OR REPLACE FUNCTION reject_mstr_btc_source_audit_mutation()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    RAISE EXCEPTION '% is append-only', TG_TABLE_NAME
        USING ERRCODE = '55000';
END;
$$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_trigger
        WHERE tgrelid = 'mstr_btc_source_events'::regclass
          AND tgname = 'trg_mstr_btc_source_events_append_only'
          AND NOT tgisinternal
    ) THEN
        CREATE TRIGGER trg_mstr_btc_source_events_append_only
        BEFORE UPDATE OR DELETE ON mstr_btc_source_events
        FOR EACH ROW
        EXECUTE FUNCTION reject_mstr_btc_source_audit_mutation();
    END IF;

    IF NOT EXISTS (
        SELECT 1
        FROM pg_trigger
        WHERE tgrelid = 'mstr_btc_fact_candidates'::regclass
          AND tgname = 'trg_mstr_btc_fact_candidates_append_only'
          AND NOT tgisinternal
    ) THEN
        CREATE TRIGGER trg_mstr_btc_fact_candidates_append_only
        BEFORE UPDATE OR DELETE ON mstr_btc_fact_candidates
        FOR EACH ROW
        EXECUTE FUNCTION reject_mstr_btc_source_audit_mutation();
    END IF;

    IF NOT EXISTS (
        SELECT 1
        FROM pg_trigger
        WHERE tgrelid = 'mstr_btc_processing_results'::regclass
          AND tgname = 'trg_mstr_btc_processing_results_append_only'
          AND NOT tgisinternal
    ) THEN
        CREATE TRIGGER trg_mstr_btc_processing_results_append_only
        BEFORE UPDATE OR DELETE ON mstr_btc_processing_results
        FOR EACH ROW
        EXECUTE FUNCTION reject_mstr_btc_source_audit_mutation();
    END IF;
END;
$$;
