-- Additive source-neutral notification outbox.
-- Source ingestion writes confirmed events here only after canonical facts are
-- durable. A separate worker delivers Telegram messages asynchronously.

CREATE TABLE IF NOT EXISTS source_notification_outbox (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    notification_key text NOT NULL,
    source_name text NOT NULL,
    scope_id text NOT NULL,
    event_kind text NOT NULL,
    message_text text NOT NULL,
    source_url text NOT NULL,
    status text NOT NULL DEFAULT 'PENDING'
        CHECK (status IN ('PENDING', 'SENDING', 'SENT', 'FAILED')),
    attempt_count integer NOT NULL DEFAULT 0
        CHECK (attempt_count >= 0),
    available_at timestamptz NOT NULL DEFAULT now(),
    lease_until timestamptz,
    last_error_code text,
    sent_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CHECK (length(notification_key) > 0),
    CHECK (length(source_name) > 0),
    CHECK (length(scope_id) > 0),
    CHECK (length(event_kind) > 0),
    CHECK (length(message_text) > 0),
    CHECK (source_url LIKE 'https://%')
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_source_notification_outbox_key
    ON source_notification_outbox (notification_key);

CREATE INDEX IF NOT EXISTS ix_source_notification_outbox_dispatch
    ON source_notification_outbox (
        status,
        available_at,
        lease_until,
        id
    );
