-- Additive research catalog for upcoming and historical earnings releases.
-- The catalog is informational: it does not arm source polling, create an
-- execution profile, or submit an order.

CREATE TABLE IF NOT EXISTS earnings_release_catalog (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_key text NOT NULL,
    ticker text NOT NULL,
    release_date date NOT NULL,
    market_session text NOT NULL
        CHECK (
            market_session IN (
                'PRE_MARKET',
                'POST_MARKET',
                'UNKNOWN'
            )
        ),
    scheduled_release_at timestamptz,
    conference_call_at timestamptz,
    schedule_status text NOT NULL DEFAULT 'CONFIRMED'
        CHECK (
            schedule_status IN (
                'CONFIRMED',
                'ESTIMATED',
                'REPORTED',
                'CANCELLED'
            )
        ),
    schedule_source_url text NOT NULL,
    integration_status text NOT NULL
        CHECK (
            integration_status IN (
                'PARSER_ONLY',
                'NEEDS_DOCUMENT_RESOLVER',
                'NEEDS_LISTING_ADAPTER',
                'SOURCE_BLOCKED',
                'RESEARCH_PENDING'
            )
        ),
    document_format text NOT NULL
        CHECK (
            document_format IN (
                'FULL_HTML',
                'PDF',
                'LINK_ONLY',
                'MIXED',
                'UNKNOWN'
            )
        ),
    metric_options jsonb NOT NULL DEFAULT '{}'::jsonb,
    source_options jsonb NOT NULL DEFAULT '[]'::jsonb,
    notes text,
    verified_at timestamptz NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CHECK (length(event_key) > 0),
    CHECK (ticker ~ '^[A-Z0-9.-]{1,16}$'),
    CHECK (schedule_source_url LIKE 'https://%'),
    CHECK (jsonb_typeof(metric_options) = 'object'),
    CHECK (jsonb_typeof(source_options) = 'array')
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_earnings_release_catalog_event_key
    ON earnings_release_catalog (event_key);

CREATE UNIQUE INDEX IF NOT EXISTS ux_earnings_release_catalog_ticker_date
    ON earnings_release_catalog (ticker, release_date);

CREATE INDEX IF NOT EXISTS ix_earnings_release_catalog_schedule
    ON earnings_release_catalog (
        release_date,
        market_session,
        ticker
    );

CREATE INDEX IF NOT EXISTS ix_earnings_release_catalog_readiness
    ON earnings_release_catalog (
        integration_status,
        release_date,
        ticker
    );
