-- Additive lifecycle scheduling for source-neutral execution profiles.
-- Existing profile columns and legacy tables are intentionally untouched.

CREATE TABLE IF NOT EXISTS resolution_profile_schedules (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    schedule_key text NOT NULL,
    profile_key text NOT NULL
        REFERENCES resolution_execution_profiles (profile_key)
        ON DELETE RESTRICT,
    automation_mode text NOT NULL DEFAULT 'MANUAL'
        CHECK (
            automation_mode IN (
                'MANUAL',
                'AUTO_PREFLIGHT',
                'AUTO_LIVE'
            )
        ),
    preflight_at timestamptz NOT NULL,
    activate_at timestamptz NOT NULL,
    deactivate_at timestamptz NOT NULL,
    state text NOT NULL DEFAULT 'PENDING'
        CHECK (
            state IN (
                'PENDING',
                'PREFLIGHTING',
                'READY',
                'ACTIVE',
                'EXPIRED',
                'BLOCKED'
            )
        ),
    preflight_request_id text,
    preflight_requested_at timestamptz,
    preflight_lease_until timestamptz,
    readiness_checked_at timestamptz,
    readiness_valid_until timestamptz,
    readiness_evidence jsonb NOT NULL DEFAULT '{}'::jsonb,
    last_error_code text,
    metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CHECK (length(schedule_key) > 0),
    CHECK (preflight_at <= activate_at),
    CHECK (activate_at < deactivate_at),
    CHECK (
        readiness_valid_until IS NULL
        OR readiness_checked_at IS NOT NULL
    ),
    CHECK (
        readiness_valid_until IS NULL
        OR readiness_valid_until > readiness_checked_at
    )
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_resolution_profile_schedules_key
    ON resolution_profile_schedules (schedule_key);

CREATE UNIQUE INDEX IF NOT EXISTS ux_resolution_profile_schedules_profile
    ON resolution_profile_schedules (profile_key);

CREATE INDEX IF NOT EXISTS ix_resolution_profile_schedules_due
    ON resolution_profile_schedules (
        state,
        automation_mode,
        preflight_at,
        activate_at,
        deactivate_at
    );

CREATE INDEX IF NOT EXISTS ix_resolution_profile_schedules_preflight
    ON resolution_profile_schedules (
        state,
        preflight_lease_until,
        preflight_requested_at
    );

CREATE TABLE IF NOT EXISTS resolution_profile_schedule_events (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_key text NOT NULL,
    schedule_id bigint NOT NULL
        REFERENCES resolution_profile_schedules (id)
        ON DELETE RESTRICT,
    schedule_key text NOT NULL,
    profile_key text NOT NULL,
    previous_state text,
    next_state text NOT NULL,
    event_kind text NOT NULL,
    reason_code text,
    metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
    notification_enqueued_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now(),
    CHECK (length(event_key) > 0),
    CHECK (length(schedule_key) > 0),
    CHECK (length(profile_key) > 0),
    CHECK (length(event_kind) > 0),
    CHECK (
        previous_state IS NULL
        OR previous_state IN (
            'PENDING',
            'PREFLIGHTING',
            'READY',
            'ACTIVE',
            'EXPIRED',
            'BLOCKED'
        )
    ),
    CHECK (
        next_state IN (
            'PENDING',
            'PREFLIGHTING',
            'READY',
            'ACTIVE',
            'EXPIRED',
            'BLOCKED'
        )
    )
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_resolution_profile_schedule_events_key
    ON resolution_profile_schedule_events (event_key);

CREATE INDEX IF NOT EXISTS ix_resolution_profile_schedule_events_notify
    ON resolution_profile_schedule_events (
        notification_enqueued_at,
        id
    );
