-- Additive liveness gate for automatic execution-profile activation.

CREATE TABLE IF NOT EXISTS resolution_runtime_heartbeats (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    runtime_key text NOT NULL,
    mode text NOT NULL
        CHECK (mode IN ('shadow', 'preflight', 'live')),
    supervision_enabled boolean NOT NULL,
    trading_enabled boolean NOT NULL,
    process_started_at timestamptz NOT NULL,
    last_seen_at timestamptz NOT NULL,
    metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CHECK (length(runtime_key) > 0),
    CHECK (last_seen_at >= process_started_at)
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_resolution_runtime_heartbeats_key
    ON resolution_runtime_heartbeats (runtime_key);

CREATE INDEX IF NOT EXISTS ix_resolution_runtime_heartbeats_seen
    ON resolution_runtime_heartbeats (last_seen_at);
