-- Additive source-neutral journal for evaluating each trading run.
-- Existing source, strategy, profile, claim, and order tables are untouched.

CREATE TABLE IF NOT EXISTS resolution_run_journal (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    journal_key text NOT NULL,
    scope_id text NOT NULL,
    profile_key text,
    schedule_key text,
    source_kind text NOT NULL,
    source_provider text,
    source_event_ref text,
    fact_ref text,
    execution_claim_ref text,
    live_block text,
    block_id text,
    selected_outcome text
        CHECK (selected_outcome IN ('YES', 'NO')),
    direction_status text NOT NULL DEFAULT 'UNKNOWN'
        CHECK (
            direction_status IN ('UNKNOWN', 'CORRECT', 'WRONG')
        ),
    execution_status text NOT NULL DEFAULT 'UNKNOWN'
        CHECK (
            execution_status IN (
                'UNKNOWN',
                'NOT_ATTEMPTED',
                'REJECTED',
                'ACCEPTED_OPEN',
                'PARTIALLY_FILLED',
                'FILLED',
                'CANCELLED',
                'ERROR'
            )
        ),
    latency_status text NOT NULL DEFAULT 'UNKNOWN'
        CHECK (
            latency_status IN ('UNKNOWN', 'FAST', 'TOO_SLOW')
        ),
    overall_result text NOT NULL DEFAULT 'PENDING'
        CHECK (
            overall_result IN (
                'PENDING',
                'SUCCESS',
                'LATENCY_MISS',
                'MISSED_EXECUTION',
                'WRONG_DIRECTION',
                'ERROR'
            )
        ),
    desired_price numeric(20, 10)
        CHECK (
            desired_price IS NULL
            OR (desired_price > 0 AND desired_price < 1)
        ),
    effective_price numeric(20, 10)
        CHECK (
            effective_price IS NULL
            OR (effective_price > 0 AND effective_price < 1)
        ),
    quantity numeric(38, 18)
        CHECK (quantity IS NULL OR quantity > 0),
    matched_quantity numeric(38, 18)
        CHECK (matched_quantity IS NULL OR matched_quantity >= 0),
    source_published_at timestamptz,
    source_detected_at timestamptz,
    claim_created_at timestamptz,
    exchange_completed_at timestamptz,
    first_order_observed_at timestamptz,
    last_order_observed_at timestamptz,
    source_latency_ms bigint
        CHECK (source_latency_ms IS NULL OR source_latency_ms >= 0),
    decision_latency_ms bigint
        CHECK (decision_latency_ms IS NULL OR decision_latency_ms >= 0),
    exchange_latency_ms bigint
        CHECK (exchange_latency_ms IS NULL OR exchange_latency_ms >= 0),
    source_url text,
    market_url text,
    error_stage text,
    error_code text,
    errors jsonb NOT NULL DEFAULT '[]'::jsonb
        CHECK (jsonb_typeof(errors) = 'array'),
    classification_reason text NOT NULL,
    details jsonb NOT NULL DEFAULT '{}'::jsonb
        CHECK (jsonb_typeof(details) = 'object'),
    finalized_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CHECK (length(journal_key) > 0),
    CHECK (length(scope_id) > 0),
    CHECK (length(source_kind) > 0),
    CHECK (length(classification_reason) > 0),
    CHECK (
        matched_quantity IS NULL
        OR quantity IS NULL
        OR matched_quantity <= quantity
    ),
    CHECK (
        source_detected_at IS NULL
        OR source_published_at IS NULL
        OR source_detected_at >= source_published_at
    ),
    CHECK (
        last_order_observed_at IS NULL
        OR first_order_observed_at IS NULL
        OR last_order_observed_at >= first_order_observed_at
    ),
    CHECK (
        source_url IS NULL
        OR source_url LIKE 'https://%'
    ),
    CHECK (
        market_url IS NULL
        OR market_url LIKE 'https://%'
    )
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_resolution_run_journal_key
    ON resolution_run_journal (journal_key);

CREATE INDEX IF NOT EXISTS ix_resolution_run_journal_scope
    ON resolution_run_journal (scope_id, updated_at DESC);

CREATE INDEX IF NOT EXISTS ix_resolution_run_journal_result
    ON resolution_run_journal (
        overall_result,
        latency_status,
        updated_at DESC
    );

CREATE INDEX IF NOT EXISTS ix_resolution_run_journal_block
    ON resolution_run_journal (block_id, live_block, updated_at DESC);

CREATE TABLE IF NOT EXISTS resolution_run_journal_events (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_key text NOT NULL,
    journal_id bigint NOT NULL
        REFERENCES resolution_run_journal(id)
        ON DELETE RESTRICT,
    event_kind text NOT NULL,
    stage text NOT NULL,
    event_status text NOT NULL,
    latency_ms bigint
        CHECK (latency_ms IS NULL OR latency_ms >= 0),
    error_code text,
    details jsonb NOT NULL DEFAULT '{}'::jsonb
        CHECK (jsonb_typeof(details) = 'object'),
    occurred_at timestamptz NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    CHECK (length(event_key) > 0),
    CHECK (length(event_kind) > 0),
    CHECK (length(stage) > 0),
    CHECK (length(event_status) > 0)
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_resolution_run_journal_events_key
    ON resolution_run_journal_events (event_key);

CREATE INDEX IF NOT EXISTS ix_resolution_run_journal_events_timeline
    ON resolution_run_journal_events (journal_id, occurred_at, id);
