-- Additive source-path telemetry for earnings ingestion.
-- Existing earnings and legacy objects remain structurally unchanged.

CREATE TABLE IF NOT EXISTS earnings_source_processing_telemetry (
    source_event_id bigint PRIMARY KEY
        REFERENCES earnings_source_events(id),
    source_transport text NOT NULL,
    transport_observed_at timestamptz NOT NULL,
    document_fetch_started_at timestamptz,
    document_fetch_completed_at timestamptz,
    document_fetch_route text,
    parse_started_at timestamptz,
    parse_completed_at timestamptz,
    fact_persisted_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS
    ix_earnings_source_processing_telemetry_transport
    ON earnings_source_processing_telemetry (
        source_transport,
        transport_observed_at
    );

CREATE TABLE IF NOT EXISTS earnings_source_transport_observations (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_event_id bigint NOT NULL
        REFERENCES earnings_source_events(id),
    transport text NOT NULL,
    first_observed_at timestamptz NOT NULL,
    last_observed_at timestamptz NOT NULL,
    observation_count bigint NOT NULL DEFAULT 1
        CHECK (observation_count > 0),
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CHECK (last_observed_at >= first_observed_at)
);

CREATE UNIQUE INDEX IF NOT EXISTS
    ux_earnings_source_transport_observations_event_transport
    ON earnings_source_transport_observations (
        source_event_id,
        transport
    );

CREATE INDEX IF NOT EXISTS
    ix_earnings_source_transport_observations_timing
    ON earnings_source_transport_observations (
        transport,
        first_observed_at
    );

INSERT INTO earnings_source_processing_telemetry (
    source_event_id,
    source_transport,
    transport_observed_at
)
SELECT
    id,
    'legacy_unknown',
    received_at
FROM earnings_source_events
ON CONFLICT (source_event_id) DO NOTHING;

INSERT INTO earnings_source_transport_observations (
    source_event_id,
    transport,
    first_observed_at,
    last_observed_at
)
SELECT
    id,
    'legacy_unknown',
    received_at,
    received_at
FROM earnings_source_events
ON CONFLICT (source_event_id, transport) DO NOTHING;
