-- Additive parser-version retry ledger for earnings source events.
-- Existing source-event and fact rows remain unchanged.

CREATE TABLE IF NOT EXISTS earnings_source_parse_attempts (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_event_id bigint NOT NULL
        REFERENCES earnings_source_events(id),
    parser_name text NOT NULL,
    parser_version text NOT NULL,
    status text NOT NULL DEFAULT 'CLAIMED'
        CHECK (
            status IN (
                'CLAIMED',
                'ACCEPTED',
                'NO_MATCH',
                'QUARANTINED',
                'ERROR'
            )
        ),
    attempt_count integer NOT NULL DEFAULT 1
        CHECK (attempt_count > 0),
    reason text,
    claimed_at timestamptz NOT NULL DEFAULT now(),
    completed_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS
    ux_earnings_source_parse_attempts_version
    ON earnings_source_parse_attempts (
        source_event_id,
        parser_name,
        parser_version
    );

CREATE INDEX IF NOT EXISTS ix_earnings_source_parse_attempts_status
    ON earnings_source_parse_attempts (status, claimed_at);
