REVOKE CREATE ON SCHEMA public FROM PUBLIC;
GRANT USAGE ON SCHEMA public TO codexpoly_app;

ALTER DEFAULT PRIVILEGES
    FOR ROLE codexpoly_admin
    IN SCHEMA public
    GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO codexpoly_app;

ALTER DEFAULT PRIVILEGES
    FOR ROLE codexpoly_admin
    IN SCHEMA public
    GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO codexpoly_app;
